### ISSUE TITLE
show ratio of received/parsed/dropped packets at the end of the run

### ISSUE THREAD

**Issue by rbroemeling** [fimmtiu/mysql-query-logger#1]
At the end of a `tcpdump` run, it shows some summary statistics:

```
168727 packets captured
389094 packets received by filter
220332 packets dropped by kernel
```

These statistics are really useful because they allow you to tell how "accurate" you can expect your traffic dump to be (i.e. what ratio of traffic was "missed").

This application should, if possible, do the same thing.

**Comment by fimmtiu** [comment]
Done! Thanks.
