### ISSUE TITLE
suggestion: support explicit stdout logging, instead of only implicit stdout logging

### ISSUE THREAD

**Issue by rbroemeling** [fimmtiu/mysql-query-logger#2]
It's pretty usual to use "-" in *NIX to mean "I want you to use stdin for input" or "I want you to use stdout for output", but mysql-query-logger doesn't support it. If an argument is given, it assumes that it is a file (and thus it will try to "open" the file "-" if that is the argument given).

In the case that an argument is passed in, but is "-", I suggest catching that and setting `conf.LogFile = makeLogger(os.Stdout)`, just to stay consistent with other *NIX tooling.

**Comment by fimmtiu** [comment]
Done! Thanks for the suggestion.
