### ISSUE TITLE
max_packet_size is variable

### ISSUE THREAD

**Issue by rbroemeling** [fimmtiu/mysql-query-logger#3]
In packet.go, this comment exists:

```
	// This can only happen if you have a SQL statement that's over 16 MB!
	if mp.isMultiPartPacket() {
		// FIXME store the payload and return nil
		return nil
	}
```

This is only true in _some_ environments. Both the MySQL server and the MySQL client can be configured with arbitrary maximum packet sizes. In some environments, maybe that is 16MB -- but it could also be smaller (or bigger) than that.

This is a small thing, but I just wanted to clarify that there is no firm/standard threshold here that you can depend on, I believe.

**Comment by fimmtiu** [comment]
Not so. There is some unfortunate terminological confusion here surrounding the concept of the "MySQL communication packet". From the MySQL docs:
```
A communication packet is a single SQL statement sent to the MySQL server, a single
row that is sent to the client, or a binary log event sent from a master replication
server to a slave.
```
(https://dev.mysql.com/doc/refman/5.5/en/packet-too-large.html)

The largest receivable communication packet for a server is controlled by the `max_allowed_packet` variable. However, a single "packet" may actually be broken into a series of separate packets for sending; let's refer to those individual pieces as "packet fragments". 16MB is the baked-in max size of a single packet fragment in the MySQL protocol:
https://dev.mysql.com/doc/internals/en/sending-more-than-16mbyte.html

So the comment is correct. Regardless of the size of the statement, no individual packet (fragment) which we read off the wire can contain more than 16MB of data, and the docs don't seem to allow the client to break a <16MB request into fragments.
